
<!DOCTYPE html>
<html lang="en">
<?php include_once 'header.phtml'; ?>
<body>
    <div class="container">


            <h1  style="display: inline;">Programmer helper</h1>
            <div class="login" style="display: inline;"></div>
            <?php
                if((isset($_SESSION['logged'])) and ($_SESSION['logged']==true))
                {
                    echo '<a href="/programmer-helper3/public/Login/logout">Wyloguj się</a>';
                }
                else
                {
                    echo '<a href="/programmer-helper3/public/Login">Zaloguj się</a>';  
                }
                
                echo '<p><a href="/programmer-helper3/public">Powrót</a></p>';
               
                if(isset($_SESSION['message']))
                {
                    echo $_SESSION['message'];
                    unset($_SESSION['message']);
                }
        
                $_SESSION['id_post']=$this->data['id_post'];

            echo '<div>';
				echo '<h1>'.$this->data['postTitle'].'</h1>';
				echo '<p>Posted on '.date('jS M Y', strtotime($this->data['postDate'])).'</p>';
				echo '<p>'.$this->data['postCont'].'</p>';				
			echo '</div>';
    
            echo '<p><a href="/programmer-helper3/public/Contact">Kontakt</a></p>'; 
                ?>
		

   
        <?php include_once 'footer.phtml'; ?>
    </div>
</body>
    
</html>
