<!DOCTYPE html>
<html lang="en">
<?php include_once 'header.phtml'; ?>
<body>
<div class="container">
    
    
    <?php
    
    echo '<h1>Dane kontaktowe użytkownika : '.$this->row['username'].'</h1>';

     echo '<p><a href="/programmer-helper3/public">Powrót</a></p>';
    
    echo '<div>';

				echo '<p>'.'Imię : '.$this->row['name'].'</p>';				
                echo '<p>'.'Nazwisko : '.$this->row['surname'].'</p>';		
                echo '<p>'.'Telefon : '.$this->row['phone'].'</p>';				
                echo '<p>'.'Państwo : '.$this->row['country'].'</p>';				
                echo '<p>'.'Miasto : '.$this->row['city'].'</p>';				
			    echo '</div>';
     echo '<p><a href="/programmer-helper3/public/Edit">Zaktualizuj dane</a></p>';
     
    ?>

		
		
   
<?php include_once 'footer.phtml'; ?>
</div>
</body>
</html>